server:
  port: 8085
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://www.hackerorange.com:3306/postcardcenter
    username: zhongchongtao
    password: zhongchongtao137
    druid-pool:
      max-active: 1000
